[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "ktbtracker-server"
version = "0.1.0"
description = ""
authors = [
    {name = "daviduczen-b14",email = "david.uczen@bayfourteen.com"}
]
readme = "README.md"
requires-python = ">=3.12"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.dependencies]
sqlalchemy = "^2.0.44"
pyjwt = "^2.10.1"
pymysql = "^1.1.2"
pyyaml = "^6.0.3"
fastapi = "^0.121.3"
fastapi-decorators = "^1.0.19"
firebase-admin = "^7.1.0"
pydantic = "^2.12.4"
pydantic-settings = "^2.12.0"
sqlmodel = "^0.0.27"
uvicorn = "^0.38.0"
[project.scripts]
ktbtracker-server = "ktbtracker_server.main:main"

[dependency-groups]
dev = [
    "coverage (>=7.12.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.0.1,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "tox (>=4.32.0,<5.0.0)"
]


[tool.pytest.ini_options]
addopts = "--junitxml=./xunit-result-report.xml"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s ($(filename)s:%(lineno)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
