[project]
name = "ktbtracker-server"
description = ""
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt",
    "crispy-bootstrap5",
    "django",
    "django-bootstrap5",
    "django-environ",
    "django-htmx",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt[crypto]>=5.5.1",
    "djangorestframework-stubs>=3.17.0",
    "drf-spectacular>=0.29.0",
    "gunicorn",
    "mysqlclient",
    "uvicorn",
    "uvicorn-worker",
]
authors = [
    {name = "daviduczen-b14",email = "david.uczen@bayfourteen.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Client Software",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Web Server :: Libraries"
]

[dependency-groups]
test = [
    "coverage",
    "flake8",
    "pytest",
    "pytest-cov",
    "pytest-mock"
]
lint = [
    "pylint",
    "ruff"
]
dev = [
    { include-group = "test" },
    { include-group = "lint" },
    "tox"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--junitxml=./xunit-result-report.xml"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s ($(filename)s:%(lineno)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
