# Generated by Django 6.0.2 on 2026-02-16 22:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit", models.BooleanField(default=False)),
                ("belt_rank", models.IntegerField(default=0)),
                ("cycle_cont", models.IntegerField(default=0)),
                ("essays", models.IntegerField(default=0)),
                ("exam_written", models.FloatField(default=0)),
                ("hidden", models.BooleanField(default=False)),
                ("letters", models.IntegerField(default=0)),
                ("exam_burpees", models.IntegerField(default=0)),
                ("exam_planks", models.IntegerField(default=0)),
                ("exam_pull_ups", models.IntegerField(default=0)),
                ("exam_push_ups", models.IntegerField(default=0)),
                ("exam_run", models.FloatField(default=0)),
                ("exam_sit_ups", models.IntegerField(default=0)),
                ("pre_exam_burpees", models.IntegerField(default=0)),
                ("pre_exam_planks", models.IntegerField(default=0)),
                ("pre_exam_pull_ups", models.IntegerField(default=0)),
                ("pre_exam_push_ups", models.IntegerField(default=0)),
                ("pre_exam_run", models.FloatField(default=0)),
                ("pre_exam_sit_ups", models.IntegerField(default=0)),
                ("poom", models.BooleanField(default=False)),
                ("pre_exam_written", models.FloatField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(default=0)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "ktbtracker_candidates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=255, unique=True)),
                ("cycle_end", models.DateField()),
                ("cycle_post_end", models.DateField(blank=True, null=True)),
                ("cycle_pre_start", models.DateField(blank=True, null=True)),
                ("cycle_start", models.DateField()),
                ("cycle_week_start", models.IntegerField()),
                ("burpees", models.IntegerField()),
                ("class_dream_team", models.IntegerField(default=0)),
                ("class_hyper_pro", models.IntegerField(default=0)),
                ("class_master_q", models.IntegerField(default=0)),
                ("class_pmaa", models.IntegerField(default=0)),
                ("class_saturday", models.IntegerField(default=0)),
                ("class_sparring", models.IntegerField(default=0)),
                ("class_weekday", models.IntegerField(default=0)),
                ("journals", models.IntegerField(default=0)),
                ("jumps", models.FloatField(default=0)),
                ("kicks", models.IntegerField(default=0)),
                ("leadership", models.IntegerField(default=0)),
                ("leadership2", models.IntegerField(default=0)),
                ("meditation", models.FloatField(default=0)),
                ("mentee", models.IntegerField(default=0)),
                ("mentor", models.IntegerField(default=0)),
                ("miles", models.FloatField(default=0)),
                ("planks", models.IntegerField(default=0)),
                ("poomsae", models.IntegerField(default=0)),
                ("pull_ups", models.IntegerField(default=0)),
                ("push_ups", models.IntegerField(default=0)),
                ("raok", models.IntegerField(default=0)),
                ("rolls_falls", models.IntegerField(default=0)),
                ("self_defense", models.IntegerField(default=0)),
                ("sit_ups", models.IntegerField(default=0)),
                ("sparring", models.FloatField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(default=0)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "ktbtracker_cycles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JournalPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("alias", models.CharField(max_length=255)),
                ("published", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(default=0)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "ktbtracker_journal_posts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_date", models.DateField()),
                ("burpees", models.IntegerField(default=0)),
                ("class_dream_team", models.IntegerField(default=0)),
                ("class_hyper_pro", models.IntegerField(default=0)),
                ("class_master_q", models.IntegerField(default=0)),
                ("class_pmaa", models.IntegerField(default=0)),
                ("class_saturday", models.IntegerField(default=0)),
                ("class_sparring", models.IntegerField(default=0)),
                ("class_weekday", models.IntegerField(default=0)),
                ("journals", models.IntegerField(default=0)),
                ("jumps", models.FloatField(default=0)),
                ("kicks", models.IntegerField(default=0)),
                ("leadership", models.IntegerField(default=0)),
                ("leadership2", models.IntegerField(default=0)),
                ("meditation", models.FloatField(default=0)),
                ("mentee", models.IntegerField(default=0)),
                ("mentor", models.IntegerField(default=0)),
                ("miles", models.FloatField(default=0)),
                ("planks", models.IntegerField(default=0)),
                ("poomsae", models.IntegerField(default=0)),
                ("pull_ups", models.IntegerField(default=0)),
                ("push_ups", models.IntegerField(default=0)),
                ("raok", models.IntegerField(default=0)),
                ("rolls_falls", models.IntegerField(default=0)),
                ("self_defense", models.IntegerField(default=0)),
                ("sit_ups", models.IntegerField(default=0)),
                ("sparring", models.FloatField(default=0)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(default=0)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.IntegerField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ktbtracker.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
