"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

import environ
from django.urls import register_converter

from ktbtracker import converters

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env')) # Load the .env file
env = environ.FileAwareEnv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7uur3dwa2!!6!bq3a&773z6kg241)$s=yk7l-ilxshpce#ax0r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    # -- Applications --
    'ktbtracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ktbtracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        'NAME': env('MYSQL_DATABASE'),
        'USER': env('MYSQL_USER'),
        'PASSWORD': env('MYSQL_PASSWORD'),
    }
}

AUTH_USER_MODEL = 'ktbtracker.User'


# Authentication
#

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True

FORMAT_MODULE_PATH = [
    "ktbtracker.formats"
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


LOGIN_REDIRECT_URL = '/tracking' # Redirect to home page after login
LOGIN_URL = '/accounts/login'
LOGOUT_REDIRECT_URL = '/accounts/login'
LOGOUT_URL = '/accounts/logout'


# Logging
# https://docs.djangoproject.com/en/6.0/howto/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "[%(asctime)s] [%(levelname)-8s] [%(name)s] %(message)s",
        },
        "verbose": {
            "format": "[%(asctime)s] [%(levelname)-8s] [%(name)s] %(message)s (%(filename)s:%(lineno)s)",
        },
        "call_trace": {
            "format": "[%(asctime)s] [%(levelname)-8s] %(message)s (%(pathname)s:%(lineno)s)",
        }
    },

    "handlers": {
        "console": {
            "level": "DEBUG",
            "formatter": "simple",
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": "DEBUG",
            "formatter": "verbose",
            "class": "logging.FileHandler",
            "filename": "general.log",
        },
        "call_trace": {
            "level": "DEBUG",
            "formatter": "call_trace",
            "class": "logging.FileHandler",
            "filename": "general.log",
        },
    },

    "root": {
        "level": "DEBUG",
        "handlers": ["console", "file"],
        "propagate": False,
    },

    "loggers": {
        "ktbtracker": {
            "level": "DEBUG",
            "formatter": "verbose",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "tracking": {
            "level": "DEBUG",
            "formatter": "verbose",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "call_trace": {
            "level": "DEBUG",
            "formatter": "call_trace",
            "handlers": ["file"],
            "propagate": False,
        },
        "django": {
            "level": "ERROR",
            "formatter": "verbose",
            "handlers": ["file"],
            "propagate": False,
        },
        "django.db": {
            "level": "DEBUG" if DEBUG else "ERROR",
            "formatter": "verbose",
            "handlers": ["file"],
            "propagate": False,
        },
        "django.auth": {
            "level": "DEBUG",
            "formatter": "verbose",
            "handlers": ["file"],
            "propagate": False,
        },
        "django.request": {
            "level": "DEBUG",
            "formatter": "verbose",
            "handlers": ["file"],
            "propagate": False,
        },
        "django.server": {
            "level": "INFO",
            "formatter": "verbose",
            "handlers": ["file"],
            "propagate": False,
        },
        'nplusone': {
            'handlers': ['console'],
            'level': 'WARN',
        },
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


INTERNAL_IPS = ["127.0.0.1"]

# Register the custom converter with a name (e.g., 'date')
register_converter(converters.DateConverter, 'date')
