"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

import environ
from django.urls import register_converter

from ktbtracker import converters


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

environ.Env.read_env(str(BASE_DIR / '.env')) # Load the .env file
env = environ.FileAwareEnv(
    DEBUG=(bool, False),
    PRODUCTION=(bool, False),
)
env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

PRODUCTION = env('PRODUCTION')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG') if 'DEBUG' in env else not PRODUCTION

APPEND_SLASH = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # --- Third Party Applications ---
    "django_htmx",
    "crispy_forms",
    "django_bootstrap5",
    "crispy_bootstrap5",
    "django_extensions",
    "oauth2_provider",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    # --- Applications ---
    "ktbtracker",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'ktbtracker.mobile.middleware.MobileDetectionMiddleware',
    'ktbtracker.mobile.middleware.SetFlavourMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ktbtracker.mobile.context_processors.flavour",
                "ktbtracker.mobile.context_processors.is_mobile",
            ],
        },
    },
]

TEMPLATE_LOADERS = "django_mobile.loader.Loader"

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.template.context_processors.request",
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
    "ktbtracker.mobile.context_processors.flavour",
    "ktbtracker.mobile.context_processors.is_mobile",
)

WSGI_APPLICATION = 'config.wsgi.application'


# ----------------------------------------------------------------------------------------------------------------------
#
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# ----------------------------------------------------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
    }
}

AUTH_USER_MODEL = 'ktbtracker.User'


# ----------------------------------------------------------------------------------------------------------------------
#
# Internationalization (i18n)
# https://docs.djangoproject.com/en/6.0/topics/i18n/
#
# ----------------------------------------------------------------------------------------------------------------------

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True

FORMAT_MODULE_PATH = [
    'ktbtracker.formats'
]


# ----------------------------------------------------------------------------------------------------------------------
#
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# ----------------------------------------------------------------------------------------------------------------------

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# This is the location of the static files in production (python manage.py collectstatic)
STATIC_ROOT = BASE_DIR / '..' /'staticfiles'


LOGIN_REDIRECT_URL = '/tracking' # Redirect to home page after login
LOGIN_URL = '/accounts/login'
LOGOUT_REDIRECT_URL = '/accounts/login'
LOGOUT_URL = '/accounts/logout'


#
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


INTERNAL_IPS = ["127.0.0.1"]

# Register the custom converter with a name (e.g., 'date')
register_converter(converters.DateConverter, 'date')

#
# Django REST Framework
#
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Your Project API",
    "DESCRIPTION": "Your project description",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # OTHER SETTINGS
    "COMPONENT_SPLIT_REQUEST": True,
    # Define the security scheme for Swagger UI
    'SECURITY': [{'BearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}
